version: '3.0'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tn8o4Ak9

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: tn8o4Ak9

  user-api:
    image: markliu2018/bookkeeping-user-api:latest
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: bookkeeping
      DB_USER: root
      DB_PASSWORD: tn8o4Ak9
      UPLOAD_ACCESS_KEY: XXX
      UPLOAD_SECRET_KEY: XXX
      UPLOAD_FLOW_IMAGE_BUCKET: XXX
      UPLOAD_FLOW_IMAGE_HOST: http://XXX
      UPLOAD_FLOW_IMAGE_CALL_BACK_URL: http://XXX/api/v1/flow-images/upload-callback
      INVITE_CODE: 1111

  user-fe:
    image: markliu2018/bookkeeping-user-fe:latest
    depends_on:
      - user-api
    environment:
      API_HOST: http://user-api:9092
    ports:
      - "5000:80"

volumes:
  mysql_data: